export const elements = {
    recipeForm: document.querySelector(".add__recipe--form"),
    titleInput: document.querySelector(".recipe__title--form"),
    prepTimeInput: document.querySelector(".recipe__prep--form"),
    servingsInput: document.querySelector(".recipe__servings--form"),
    ingredientsInput: document.querySelector(".recipe__ingredients--form"),
    directionsInput: document.querySelector(".recipe__directions--form"),
    dinnerTagInput: document.getElementById("dinner"),
    breakfastTagInput: document.getElementById("breakfast"),
    brunchTagInput: document.getElementById("brunch"),
    healthyTagInput: document.getElementById("healthy"),
    summerTagInput: document.getElementById("summer"),
    meatTagInput: document.getElementById("meat"),
    junkTagInput: document.getElementById("junk"),
    dessertTagInput: document.getElementById("dessert"),
    veggieTagInput: document.getElementById("veggie"),
    resultList: document.querySelector(".results__list"),
    searchResPages: document.querySelector(".results__pages"),
    recipe: document.querySelector(".recipe"),
    tagsPickFrom: document.querySelector(".form__tags--pick"),
    tagsButtons: document.querySelector(".tags__pick")
}